package cz.uhk.fim.kikm.navigation.util;

/**
 * @author Bc. Radek Brůha <bruhara1@uhk.cz>
 */
public class Settings {
	public static final String
			SQLITE_DATABASE_NAME = "FingerPrint",
			COUCH_DATABASE_NAME = SQLITE_DATABASE_NAME.toLowerCase(),
			COUCH_DATABASE_URL = "http://beacon.uhk.cz/fingerprintgw",
			SEARCH_SERVER_URL = "http://beacon.uhk.cz/location-server",
			LOGIN_SERVER_URL = "http://beacon.uhk.cz/auth";
	
	public static final String[]
			CRASH_EMAIL = { "bruhara1@uhk.cz" };
	
	public static final int
			COUCH_DATABASE_BATCH_SIZE = 10,
			MAXIMUM_PARTICLES = 3721,
			SEARCH_ALGORITHM_NEIGHBOURS = 10,
			SEARCH_ALGORITHM_NEIGHBOURS_WIRELESS = 11,
			SEARCH_ALGORITHM_NEIGHBOURS_BlUETOOTH = 12,
			SEARCH_ALGORITHM_NEIGHBOURS_CELLULAR = 13,
			SEARCH_ALGORITHM_NEIGHBOURS_TOGETHER = 14,
			SEARCH_ALGORITHM_PARTICLES = 20,
			SEARCH_ALGORITHM_PARTICLES_WIRELESS = 21,
			SEARCH_ALGORITHM_PARTICLES_BLUETOOTH = 22,
			SEARCH_ALGORITHM_PARTICLES_CELLULAR = 23,
			SEARCH_ALGORITHM_PARTICLES_TOGETHER = 24,
			SEARCH_ALGORITHM_CUSTOM = 30,
			SEARCH_ALGORITHM_CUSTOM_WIRELESS = 31,
			SEARCH_ALGORITHM_CUSTOM_BLUETOOTH = 32,
			SEARCH_ALGORITHM_CUSTOM_CELLULAR = 33,
			SEARCH_ALGORITHM_CUSTOM_TOGETHER = 34,
			SEARCH_ALGORITHM_TOGETHER = 100;
	
	public static final float
			DIFFERENCE_TOLERANCE_LOW = 2.5f,
			DIFFERENCE_TOLERANCE_HIGH = 5f;
	
	public static int
			CREATING_TIME = 30000,
			CREATING_REPETITION_DOZEN = 0,
			CREATING_REPETITION_UNIT = 1,
			SEARCH_ALGORITHM = SEARCH_ALGORITHM_NEIGHBOURS;
	
	public static boolean
			SHOW_FINGERPRINT = true;
}